[project]
name = "mcp-server-deepdive-functionality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=2.14.4",
    "mcp[cli]>=1.26.0",
    "pillow>=12.1.0",
    "pyautogui>=0.9.54",
    "pyscreeze>=1.0.1",
]
